add simple timeout API
alexis-mignon/python-flickr-api pull request #132
Opened 2023-01-26 22:12 UTC by smontanaro

PR in response to 

https://github.com/alexis-mignon/python-flickr-api/issues/131

2023-01-27 16:03 UTC, beaufour requested changes
Overall, this looks great. Two minor tweaks and then let's get it in.

2023-01-27 16:03 UTC, beaufour commented on flickr_api/method_call.py
> +TIMEOUT = None
Let's set it to default of 10s. It's pretty conservative. If a server hasn't sent anything for 10 seconds, something's quite wrong. You can add a comment with the link to the `requests` documentation as a bonus.

2023-01-27 22:06 UTC, smontanaro commented
I don't know how to tell GitHub that the requested changes have been made, but the PR has been updated.

2023-01-30 15:24 UTC, beaufour commented
This looks great. Thanks for the patch @smontanaro !

2023-01-30 15:25 UTC, merged